version: '3.8'

services:
  # image project
  app:
    image: ${DOCKER_USERNAME}/meuapp:latest
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - storage-data:/var/www/storage
      - cache-data:/var/www/bootstrap/cache
    depends_on:
      - redis
      - db
    networks:
      - laravel
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - code-volume:/var/www:ro
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel

  # db mysql
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    command: --default-authentication-plugin=mysql_native_password

  # redis
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  storage-data:
  cache-data:
  app-code:
